resources:
- repo: self

variables:
  ArtifactsDirectoryName: 'artifacts'
  BuildConfiguration: 'Debug'
  BuildPlatform: 'Any CPU'
  MSBuildArgs: '"/BinaryLogger:$(Build.SourcesDirectory)\$(ArtifactsDirectoryName)\msbuild.binlog"'

trigger:
  batch: 'true'
  branches:
    include:
    - 'main'
    - 'release/*'
  paths:
    exclude:
    - '*.md'
pr:
  branches:
    include:
    - 'main'
    - 'release/*'
  paths:
    exclude:
    - '*.md'

jobs:
- job: LinuxBuild
  displayName: 'Build (Linux)'
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET'
    inputs:
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      arguments: '$(MSBuildArgs)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(ArtifactsDirectoryName)'
      ArtifactName: '$(ArtifactsDirectoryName)-linux'
    condition: always()